/-
Copyright (c) 2026 Graph Container formalization team. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Graph Container formalization team
-/
module

public import GraphContainer.Intersecting.Basic
public import Mathlib.Analysis.Matrix.Spectrum
public import Mathlib.Combinatorics.SimpleGraph.AdjMatrix

import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.Data.Nat.Choose.Sum

/-!
# The least eigenvalue of a Kneser graph

This file supplies the spectral input used by the supersaturation argument.  The proof uses the
standard incidence filtration.  If `u_J` is the indicator of the `k`-sets containing `J`, then the
Kneser adjacency operator sends `u_J`, modulo indicators belonging to proper subsets of `J`, to

`(-1) ^ #J * choose (n - k - #J) (k - #J) * u_J`.

Consequently every adjacency eigenvalue occurs among these `k + 1` displayed values.  The value
with index one is attained by the difference of two one-point incidence vectors and is the least
one when `2 * k + 1 <= n`.
-/

@[expose] public section

open Finset Matrix Module End

namespace SimpleGraph.KneserCounting

noncomputable section

/-- The indicator of the `k`-sets which contain `J`. -/
private def incidenceVector (n k : ℕ) (J : Finset (Fin n)) : Vertex n k → ℝ :=
  fun A ↦ if J ⊆ (A : Finset (Fin n)) then 1 else 0

/-- The incidence filtration generated by indicators indexed by sets of size at most `i`. -/
private def incidenceSpace (n k i : ℕ) : Submodule ℝ (Vertex n k → ℝ) :=
  Submodule.span ℝ {x | ∃ J : Finset (Fin n), #J ≤ i ∧ incidenceVector n k J = x}

/-- The adjacency operator of the Kneser graph. -/
private def adjacencyOperator (n k : ℕ) :
    (Vertex n k → ℝ) →ₗ[ℝ] (Vertex n k → ℝ) :=
  ((graph n k).adjMatrix ℝ).toLin'

/-- The standard list of Kneser adjacency eigenvalues. -/
private def kneserEigenvalue (n k i : ℕ) : ℝ :=
  (-1 : ℝ) ^ i * ((n - k - i).choose (k - i) : ℝ)

private lemma incidenceSpace_mono {n k i j : ℕ} (hij : i ≤ j) :
    incidenceSpace n k i ≤ incidenceSpace n k j := by
  apply Submodule.span_mono
  rintro x ⟨J, hJ, rfl⟩
  exact ⟨J, hJ.trans hij, rfl⟩

private lemma incidenceVector_mem (n k : ℕ) {i : ℕ} {J : Finset (Fin n)} (hJ : #J ≤ i) :
    incidenceVector n k J ∈ incidenceSpace n k i := by
  exact Submodule.subset_span ⟨J, hJ, rfl⟩

private lemma incidenceSpace_top (n k : ℕ) : incidenceSpace n k k = ⊤ := by
  apply top_unique
  intro x _
  classical
  have hsingle (A : Vertex n k) :
      Pi.single A (x A) = (x A) • incidenceVector n k (A : Finset (Fin n)) := by
    funext B
    by_cases hAB : A = B
    · subst B
      simp [incidenceVector]
    · have hnsub : ¬ (A : Finset (Fin n)) ⊆ (B : Finset (Fin n)) := by
        intro hsub
        apply hAB
        apply Subtype.ext
        apply Finset.eq_of_subset_of_card_le hsub
        simp [Set.powersetCard.card_eq A, Set.powersetCard.card_eq B]
      simp [hAB, incidenceVector, hnsub]
  rw [← Finset.univ_sum_single x]
  exact Submodule.sum_mem _ fun A _ ↦ by
    rw [hsingle]
    have hcard : #(A : Finset (Fin n)) ≤ k := by
      rw [Set.powersetCard.card_eq A]
    exact (incidenceSpace n k k).smul_mem (x A)
      (incidenceVector_mem n k hcard)

private lemma choose_diagonal_mono (a b t : ℕ) :
    a.choose b ≤ (a + t).choose (b + t) := by
  induction t with
  | zero => simp
  | succ t ih =>
      calc
        a.choose b ≤ (a + t).choose (b + t) := ih
        _ ≤ (a + t + 1).choose (b + t + 1) := by
          rw [Nat.choose_succ_succ']
          omega
        _ = (a + (t + 1)).choose (b + (t + 1)) := by simp [Nat.add_assoc]

private lemma inclusion_exclusion_incidence (n k : ℕ) (J : Finset (Fin n))
    (A : Vertex n k) :
    ∑ L ∈ J.powerset,
        (-1 : ℝ) ^ #L * incidenceVector n k L A =
      if Disjoint J (A : Finset (Fin n)) then 1 else 0 := by
  classical
  have hfilter :
      J.powerset.filter (· ⊆ (A : Finset (Fin n))) =
        (J ∩ (A : Finset (Fin n))).powerset := by
    ext L
    simp only [mem_filter, mem_powerset, subset_inter_iff]
  simp only [incidenceVector]
  simp_rw [mul_ite, mul_one, mul_zero]
  rw [← Finset.sum_filter, hfilter]
  by_cases hdis : Disjoint J (A : Finset (Fin n))
  · have hinter : J ∩ (A : Finset (Fin n)) = ∅ := Finset.disjoint_iff_inter_eq_empty.mp hdis
    simp [hdis, hinter]
  · have hinter : (J ∩ (A : Finset (Fin n))).Nonempty := by
      simpa [Finset.nonempty_iff_ne_empty, Finset.disjoint_iff_inter_eq_empty] using hdis
    rw [if_neg hdis]
    exact_mod_cast
      (Finset.sum_powerset_neg_one_pow_card_of_nonempty
        (x := J ∩ (A : Finset (Fin n))) hinter)

private lemma adjacencyOperator_apply (n k : ℕ) (x : Vertex n k → ℝ)
    (A : Vertex n k) :
    adjacencyOperator n k x A =
      ∑ B : Vertex n k, if (graph n k).Adj A B then x B else 0 := by
  simp [adjacencyOperator, Matrix.toLin'_apply, Matrix.mulVec, dotProduct,
    SimpleGraph.adjMatrix_apply]

private lemma card_disjoint_supersets
    {n k : ℕ} (A : Vertex n k) (J : Finset (Fin n))
    (hJk : #J ≤ k) (hdis : Disjoint J (A : Finset (Fin n))) :
    #((Finset.univ : Finset (Vertex n k)).filter (fun B : Vertex n k ↦
        Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) ∧
          J ⊆ (B : Finset (Fin n)))) =
      (n - k - #J).choose (k - #J) := by
  classical
  let valEmbedding : Vertex n k ↪ Finset (Fin n) :=
    ⟨fun B ↦ (B : Finset (Fin n)), fun _ _ h ↦ Subtype.ext h⟩
  let F : Finset (Vertex n k) :=
    (Finset.univ : Finset (Vertex n k)).filter (fun B : Vertex n k ↦
      Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) ∧
        J ⊆ (B : Finset (Fin n)))
  have hmap :
      F.map valEmbedding =
        (((A : Finset (Fin n)))ᶜ.powersetCard k).filter (J ⊆ ·) := by
    ext B
    simp only [F, mem_map, mem_filter, mem_univ, true_and, mem_powersetCard]
    constructor
    · rintro ⟨B', ⟨hdisAB, hJB'⟩, rfl⟩
      exact ⟨⟨fun x hxB ↦ Finset.mem_compl.mpr fun hxA ↦
        Finset.disjoint_left.mp hdisAB hxA hxB,
        Set.powersetCard.card_eq B'⟩, hJB'⟩
    · rintro ⟨⟨hBcomp, hBcard⟩, hJB⟩
      let B' : Vertex n k := ⟨B, hBcard⟩
      refine ⟨B', ⟨?_, hJB⟩, rfl⟩
      exact Finset.disjoint_left.mpr fun x hxA hxB ↦
        (Finset.mem_compl.mp (hBcomp hxB)) hxA
  have hJcomp : J ⊆ ((A : Finset (Fin n)))ᶜ := by
    intro x hxJ
    exact Finset.mem_compl.mpr fun hxA ↦ Finset.disjoint_left.mp hdis hxJ hxA
  change #F = _
  calc
    #F = #(F.map valEmbedding) := (Finset.card_map _).symm
    _ = #((((A : Finset (Fin n)))ᶜ.powersetCard k).filter (J ⊆ ·)) := by rw [hmap]
    _ = ((#((A : Finset (Fin n)))ᶜ - #J).choose (k - #J)) :=
      Finset.card_filter_powersetCard_subset J ((A : Finset (Fin n)))ᶜ k hJcomp hJk
    _ = (n - k - #J).choose (k - #J) := by
      rw [Finset.card_compl, Fintype.card_fin, Set.powersetCard.card_eq A]

private lemma adjacency_incidenceVector
    {n k : ℕ} (hk : 0 < k) (J : Finset (Fin n)) (hJk : #J ≤ k) :
    adjacencyOperator n k (incidenceVector n k J) =
      ((n - k - #J).choose (k - #J) : ℝ) •
        (fun A : Vertex n k ↦
          if Disjoint J (A : Finset (Fin n)) then 1 else 0) := by
  classical
  funext A
  rw [adjacencyOperator_apply]
  simp only [Pi.smul_apply]
  by_cases hdis : Disjoint J (A : Finset (Fin n))
  · rw [if_pos hdis]
    simp only [smul_eq_mul, mul_one, incidenceVector]
    calc
      (∑ B : Vertex n k,
          if (graph n k).Adj A B then
            (if J ⊆ (B : Finset (Fin n)) then 1 else 0)
          else 0) =
          ∑ B : Vertex n k,
            if Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) ∧
                J ⊆ (B : Finset (Fin n)) then 1 else 0 := by
            apply Finset.sum_congr rfl
            intro B _
            by_cases hadj : (graph n k).Adj A B
            · have hAB : Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) :=
                (graph_adj_iff_disjoint n k hk).mp hadj
              have hne : A ≠ B := ((graph_adj_iff n k).mp hadj).1
              simp [hne, hAB]
            · have hnAB : ¬ Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) :=
                fun hAB ↦ hadj ((graph_adj_iff_disjoint n k hk).mpr hAB)
              simp [hnAB]
      _ = (#((Finset.univ : Finset (Vertex n k)).filter (fun B : Vertex n k ↦
          Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) ∧
            J ⊆ (B : Finset (Fin n)))) : ℝ) := by simp
      _ = ((n - k - #J).choose (k - #J) : ℝ) := by
        exact_mod_cast card_disjoint_supersets A J hJk hdis
  · rw [if_neg hdis]
    simp only [smul_eq_mul, mul_zero]
    apply Finset.sum_eq_zero
    intro B _
    by_cases hadj : (graph n k).Adj A B
    · rw [if_pos hadj]
      have hAB : Disjoint (A : Finset (Fin n)) (B : Finset (Fin n)) :=
        (graph_adj_iff_disjoint n k hk).mp hadj
      have hnJB : ¬ J ⊆ (B : Finset (Fin n)) := by
        intro hJB
        apply hdis
        exact hAB.symm.mono_left hJB
      simp [incidenceVector, hnJB]
    · rw [if_neg hadj]

private lemma adjacency_incidence_expansion
    {n k : ℕ} (hk : 0 < k) (J : Finset (Fin n)) (hJk : #J ≤ k) :
    adjacencyOperator n k (incidenceVector n k J) =
      ((n - k - #J).choose (k - #J) : ℝ) •
        ∑ L ∈ J.powerset, (-1 : ℝ) ^ #L • incidenceVector n k L := by
  rw [adjacency_incidenceVector hk J hJk]
  congr 1
  funext A
  simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
  exact (inclusion_exclusion_incidence n k J A).symm

private lemma adjacency_incidence_mem
    {n k : ℕ} (hk : 0 < k) (J : Finset (Fin n)) (hJk : #J ≤ k) :
    adjacencyOperator n k (incidenceVector n k J) ∈ incidenceSpace n k #J := by
  rw [adjacency_incidence_expansion hk J hJk]
  apply Submodule.smul_mem
  apply Submodule.sum_mem
  intro L hL
  apply Submodule.smul_mem
  exact incidenceVector_mem n k (Finset.card_le_card (Finset.mem_powerset.mp hL))

private lemma adjacency_incidence_sub_eigenvalue_mem
    {n k i : ℕ} (hk : 0 < k) (hi : i ≤ k)
    (J : Finset (Fin n)) (hJi : #J = i) :
    adjacencyOperator n k (incidenceVector n k J) -
        kneserEigenvalue n k i • incidenceVector n k J ∈
      incidenceSpace n k (i - 1) := by
  have hJk : #J ≤ k := hJi.le.trans hi
  rw [adjacency_incidence_expansion hk J hJk]
  have hJmem : J ∈ J.powerset := Finset.mem_powerset.mpr Subset.rfl
  rw [← Finset.sum_erase_add _ _ hJmem]
  simp only [hJi, kneserEigenvalue, smul_add, smul_smul]
  have hcoeff :
      ((n - k - i).choose (k - i) : ℝ) * (-1 : ℝ) ^ i =
        (-1 : ℝ) ^ i * ((n - k - i).choose (k - i) : ℝ) := by ring
  rw [hcoeff, add_sub_cancel_right]
  apply Submodule.smul_mem
  apply Submodule.sum_mem
  intro L hL
  apply Submodule.smul_mem
  have hLpow : L ∈ J.powerset := (Finset.mem_erase.mp hL).2
  have hLne : L ≠ J := (Finset.mem_erase.mp hL).1
  have hLlt : #L < #J :=
    Finset.card_lt_card (Finset.ssubset_iff_subset_ne.mpr
      ⟨Finset.mem_powerset.mp hLpow, hLne⟩)
  apply incidenceVector_mem n k
  omega

private lemma adjacency_incidence_zero_layer
    {n k : ℕ} (hk : 0 < k) (J : Finset (Fin n)) (hJ : #J ≤ 0) :
    adjacencyOperator n k (incidenceVector n k J) =
      kneserEigenvalue n k 0 • incidenceVector n k J := by
  have hJempty : J = ∅ := Finset.card_eq_zero.mp (Nat.eq_zero_of_le_zero hJ)
  subst J
  rw [adjacency_incidence_expansion hk ∅ (by simp)]
  simp [kneserEigenvalue]

private lemma adjacency_eq_eigenvalue_on_zero_layer
    {n k : ℕ} (hk : 0 < k) {x : Vertex n k → ℝ}
    (hx : x ∈ incidenceSpace n k 0) :
    adjacencyOperator n k x = kneserEigenvalue n k 0 • x := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨J, hJ, rfl⟩
      exact adjacency_incidence_zero_layer hk J hJ
  | zero => simp
  | add x y _ _ hx hy => simp [map_add, hx, hy, smul_add]
  | smul a x _ hx => simp [map_smul, hx, smul_smul, mul_comm]

private lemma adjacency_sub_eigenvalue_mem_prev
    {n k i : ℕ} (hk : 0 < k) (hi : i ≤ k) (hi0 : 0 < i)
    {x : Vertex n k → ℝ} (hx : x ∈ incidenceSpace n k i) :
    adjacencyOperator n k x - kneserEigenvalue n k i • x ∈
      incidenceSpace n k (i - 1) := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      rcases hx with ⟨J, hJi, rfl⟩
      by_cases hcard : #J = i
      · exact adjacency_incidence_sub_eigenvalue_mem hk hi J hcard
      · have hcardlt : #J < i := lt_of_le_of_ne hJi hcard
        apply Submodule.sub_mem
        · exact incidenceSpace_mono (by omega) <|
            adjacency_incidence_mem hk J (hJi.trans hi)
        · exact (incidenceSpace n k (i - 1)).smul_mem _
            (incidenceVector_mem n k (by omega))
  | zero => simp
  | add x y _ _ hx hy =>
      simpa [map_add, smul_add, add_sub_add_comm] using
        (incidenceSpace n k (i - 1)).add_mem hx hy
  | smul a x _ hx =>
      simpa [map_smul, smul_smul, mul_comm, smul_sub] using
        (incidenceSpace n k (i - 1)).smul_mem a hx

private lemma hasEigenvalue_eq_kneserEigenvalue
    {n k : ℕ} (hk : 0 < k) {μ : ℝ}
    (hμ : Module.End.HasEigenvalue (adjacencyOperator n k) μ) :
    ∃ i ≤ k, μ = kneserEigenvalue n k i := by
  classical
  obtain ⟨x, hx⟩ := hμ.exists_hasEigenvector
  have hxne : x ≠ 0 := hx.2
  have hxapply : adjacencyOperator n k x = μ • x := hx.apply_eq_smul
  let P : ℕ → Prop := fun i ↦ x ∈ incidenceSpace n k i
  have hP : ∃ i, P i := by
    refine ⟨k, ?_⟩
    dsimp [P]
    rw [incidenceSpace_top]
    exact Submodule.mem_top
  let i := Nat.find hP
  have hxi : x ∈ incidenceSpace n k i := Nat.find_spec hP
  have hik : i ≤ k := Nat.find_min' hP (by
    dsimp [P]
    rw [incidenceSpace_top]
    exact Submodule.mem_top)
  refine ⟨i, hik, ?_⟩
  by_cases hi : i = 0
  · have hxi0 : x ∈ incidenceSpace n k 0 := by simpa [hi] using hxi
    have hxzero := adjacency_eq_eigenvalue_on_zero_layer hk hxi0
    simpa [hi] using smul_left_injective ℝ hxne (hxapply.symm.trans hxzero)
  · have hi0 : 0 < i := Nat.pos_of_ne_zero hi
    have hrem := adjacency_sub_eigenvalue_mem_prev hk hik hi0 hxi
    rw [hxapply, ← sub_smul] at hrem
    by_contra hne
    have hscalar : μ - kneserEigenvalue n k i ≠ 0 := sub_ne_zero.mpr hne
    have hxprev := (incidenceSpace n k (i - 1)).smul_mem
      (μ - kneserEigenvalue n k i)⁻¹ hrem
    simp only [smul_smul, inv_mul_cancel₀ hscalar, one_smul] at hxprev
    exact Nat.find_min hP (by omega) hxprev

private lemma kneserEigenvalue_one_le
    {n k i : ℕ} (hnk : 2 * k + 1 ≤ n) (hi : i ≤ k) :
    kneserEigenvalue n k 1 ≤ kneserEigenvalue n k i := by
  rcases neg_one_pow_eq_or ℝ i with hsign | hsign
  · have hleft : 0 ≤ ((n - k - 1).choose (k - 1) : ℝ) := by positivity
    have hright : 0 ≤ ((n - k - i).choose (k - i) : ℝ) := by positivity
    unfold kneserEigenvalue
    norm_num
    rw [hsign]
    nlinarith
  · have hi0 : 0 < i := by
      by_contra h
      have : i = 0 := Nat.eq_zero_of_not_pos h
      subst i
      have hone : (1 : ℝ) ≠ -1 := by norm_num
      exact hone (by simpa using hsign)
    have ha : n - k - i + (i - 1) = n - k - 1 := by omega
    have hb : k - i + (i - 1) = k - 1 := by omega
    have hchoose := choose_diagonal_mono (n - k - i) (k - i) (i - 1)
    rw [ha, hb] at hchoose
    unfold kneserEigenvalue
    norm_num
    rw [hsign]
    norm_num
    exact_mod_cast hchoose

private lemma kneserEigenvalue_one_hasEigenvalue
    {n k : ℕ} (hk : 0 < k) (hnk : 2 * k + 1 ≤ n) :
    Module.End.HasEigenvalue (adjacencyOperator n k) (kneserEigenvalue n k 1) := by
  classical
  have hn : 0 < n := by omega
  have hn2 : 2 ≤ n := by omega
  let p : Fin n := ⟨0, hn⟩
  let q : Fin n := ⟨1, by omega⟩
  have hpq : p ≠ q := by simp [p, q]
  let v : Vertex n k → ℝ :=
    incidenceVector n k {p} - incidenceVector n k {q}
  have hp := adjacency_incidenceVector (n := n) (k := k) hk {p} (by simp; omega)
  have hq := adjacency_incidenceVector (n := n) (k := k) hk {q} (by simp; omega)
  have hvapply : adjacencyOperator n k v = kneserEigenvalue n k 1 • v := by
    dsimp [v]
    rw [map_sub, hp, hq]
    funext A
    by_cases hpA : p ∈ (A : Finset (Fin n)) <;>
      by_cases hqA : q ∈ (A : Finset (Fin n)) <;>
        simp [incidenceVector, kneserEigenvalue, hpA, hqA]
  let s : Finset (Fin n) := ((Finset.univ : Finset (Fin n)).erase p).erase q
  have hps : p ∉ s := by simp [s]
  have hqs : q ∉ s := by simp [s]
  have hscard : #s = n - 2 := by
    simp [s, hpq.symm, Finset.card_erase_of_mem]
    omega
  have hkcard : k - 1 ≤ #s := by rw [hscard]; omega
  obtain ⟨T, hTs, hTcard⟩ := Finset.exists_subset_card_eq hkcard
  have hpT : p ∉ T := fun hpT ↦ hps (hTs hpT)
  have hqT : q ∉ T := fun hqT ↦ hqs (hTs hqT)
  have hAcard : #(insert p T) = k := by
    rw [Finset.card_insert_of_notMem hpT, hTcard]
    omega
  let A : Vertex n k := ⟨insert p T, hAcard⟩
  have hvA : v A = 1 := by
    simp [v, incidenceVector, A, hpq.symm, hqT]
  have hvne : v ≠ 0 := by
    intro hv
    have := congrFun hv A
    rw [hvA] at this
    simp at this
  exact Module.End.hasEigenvalue_of_hasEigenvector
    ⟨Module.End.mem_eigenspace_iff.mpr hvapply, hvne⟩

private lemma kneserEigenvalue_one_isLeast
    {n k : ℕ} (hk : 0 < k) (hnk : 2 * k + 1 ≤ n) :
    IsLeast (spectrum ℝ ((graph n k).adjMatrix ℝ)) (kneserEigenvalue n k 1) := by
  constructor
  · have heig := kneserEigenvalue_one_hasEigenvalue hk hnk
    have hmem : kneserEigenvalue n k 1 ∈ spectrum ℝ (adjacencyOperator n k) :=
      Module.End.HasEigenvalue.mem_spectrum heig
    simpa [adjacencyOperator] using hmem
  · intro μ hμ
    have hμ' : μ ∈ spectrum ℝ (adjacencyOperator n k) := by
      simpa [adjacencyOperator] using hμ
    have heig : Module.End.HasEigenvalue (adjacencyOperator n k) μ :=
      Module.End.hasEigenvalue_iff_mem_spectrum.mpr hμ'
    obtain ⟨i, hi, rfl⟩ := hasEigenvalue_eq_kneserEigenvalue hk heig
    exact kneserEigenvalue_one_le hnk hi

private lemma kneserEigenvalue_one_eq
    {n k : ℕ} (hk : 0 < k) (hnk : 2 * k + 1 ≤ n) :
    kneserEigenvalue n k 1 =
      -((k : ℝ) / (((n - k : ℕ) : ℝ)) * (regularDegree n k : ℝ)) := by
  have hnkpos : 0 < n - k := by omega
  have hidNat :
      (n - k) * (n - k - 1).choose (k - 1) =
        (n - k).choose k * k := by
    have hm : n - k - 1 + 1 = n - k := by omega
    have hk' : k - 1 + 1 = k := by omega
    simpa [hm, hk'] using Nat.add_one_mul_choose_eq (n - k - 1) (k - 1)
  have hid :
      ((n - k : ℕ) : ℝ) * ((n - k - 1).choose (k - 1) : ℝ) =
        ((n - k).choose k : ℝ) * (k : ℝ) := by
    exact_mod_cast hidNat
  have hden : (((n - k : ℕ) : ℝ)) ≠ 0 := by exact_mod_cast hnkpos.ne'
  unfold kneserEigenvalue regularDegree
  norm_num
  field_simp [hden]
  nlinarith [hid]

/-- The least adjacency eigenvalue of the Kneser graph `KG(n,k)`. -/
theorem kneser_least_eigenvalue
    {n k : ℕ} (hk : 0 < k) (hnk : 2 * k + 1 ≤ n) :
    IsLeast (spectrum ℝ ((graph n k).adjMatrix ℝ))
      (-((k : ℝ) / (((n - k : ℕ) : ℝ)) * (regularDegree n k : ℝ))) := by
  simpa [kneserEigenvalue_one_eq hk hnk] using kneserEigenvalue_one_isLeast hk hnk

end

end SimpleGraph.KneserCounting
